# .github/workflows/deploy.yml
name: Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/sewsuite-backend-production:${{ github.sha }},${{ steps.login-ecr.outputs.registry }}/sewsuite-backend-production:latest
          
      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/sewsuite-frontend-production:${{ github.sha }},${{ steps.login-ecr.outputs.registry }}/sewsuite-frontend-production:latest
          
      - name: Update ECS services
        run: |
          aws ecs update-service --cluster sewsuite-cluster-production --service sewsuite-backend-production --force-new-deployment
          aws ecs update-service --cluster sewsuite-cluster-production --service sewsuite-frontend-production --force-new-deployment